### PR TITLE
Create add new credit card page

### LINKED ISSUE #31: Add New Card
**Task title**
Add New Card page

**Task description**
This issue focuses on creating an "Add New Card" page that allows users to securely input their credit card details. 

**Subtasks**

- [ ] Form Validation: Implement robust form validation to ensure that users provide accurate and complete credit card information. Display clear error messages when incorrect data is entered.
- [ ] Confirmation and Verification: Once users submit their credit card information, they should receive a confirmation message.
- [ ] Create Cards thank page.

**Screenshots**
Capture d’écran 2023-10-15 004413
Capture d’écran 2023-10-15 004509

**Link to the component on Figma**
https://www.figma.com/file/4OUnD74RgIW6tsUFdb7gcW/Untitled?type=design&node-id=2-4711&mode=design&t=iYcMyvxa9t3sNrbw-4

### PR DESCRIPTION
**Pull request by HabchiSidAli**
Create a responsive page for users to add new credit cards to their profiles.

image

# Related Issue

- Resolve #31

### CODE REVIEW

**Review by dzc0d3r — APPROVED** [review]
Amazing work @HabchiSidAli 
Thank you

**Review by Lilicod — APPROVED** [review]
Amazing jib @HabchiSidAli, 👍 thank you

**Comment by dalilia** [comment]
good job @HabchiSidAli

**Review by meryem08 — APPROVED** [review]
Amazing job @HabchiSidAli

**Pull request merged**
