### PR TITLE
add therapist profile page

### LINKED ISSUE #20: Therapist Profile Page
**Task title**
Therapist Profile Page

**Task description**
create a  therapist Profile page 

**Subtasks**

- [x] Display user-specific data
- [x] therapist can view and edit their personal information

**Screenshots**
Capture d’écran 2023-10-14 203441

**Link to the component on Figma**
https://www.figma.com/file/4OUnD74RgIW6tsUFdb7gcW/Untitled?type=design&node-id=2-5628&mode=design&t=iYcMyvxa9t3sNrbw-4

### PR DESCRIPTION
**Pull request by dzc0d3r**
**Description**
Therapist profile page to display and edit profile informations   

# Related Issue

- Resolve #20

### CODE REVIEW

**Review by Lilicod — APPROVED** [review]
Amazing work @dzc0d3r, just one thing after editing the profile and click the save button it would be nice to show a notification indicate that the changes are saved.

**Comment by dzc0d3r** [comment]
> Amazing work @dzc0d3r, just one thing after editing the profile and click the save button it would be nice to show a notification indicate that the changes are saved.

@Lilicod for that how about we add `react-toastify` to show notifications to the users (success, errors .. etc ) and maybe replace the thank you pages too with with notifications too ?

**Comment by Lilicod** [comment]
> > Amazing work @dzc0d3r, just one thing after editing the profile and click the save button it would be nice to show a notification indicate that the changes are saved.
> 
> @Lilicod for that how about we add `react-toastify` to show notifications to the users (success, errors .. etc ) and maybe replace the thank you pages too with with notifications too ?

That's a good idea to show notification with  `react-toastify` in this case. however, I think there's some cases the thank you page is better, so maybe we shouldn't replace all of them.

**Comment by dzc0d3r** [comment]
> > > Amazing work @dzc0d3r, just one thing after editing the profile and click the save button it would be nice to show a notification indicate that the changes are saved.
> > 
> > 
> > @Lilicod for that how about we add `react-toastify` to show notifications to the users (success, errors .. etc ) and maybe replace the thank you pages too with with notifications too ?
> 
> That's a good idea to show notification with `react-toastify` in this case. however, I think there's some cases the thank you page is better, so maybe we shouldn't replace all of them.

Ok .. i updated the code with the changes above

**Review by M07am3dM — APPROVED** [review]
Amazing job @dzc0d3r, well done.

**Pull request merged**
