### PR TITLE
Create contact and contactThankYou page

### LINKED ISSUE #14: contact page
**Task title**
contact page

**Task description**
creat the contact us page

**Subtasks**

- [x] Type of contact selection section where the user can select the inquiry type.

- [x] Contact Form : Implement a user-friendly contact form with fields for users to enter their name, email address, and message.

- [x] Submission Handling : Set up a mechanism to process and manage incoming user inquiries. 

- [x] Email Integration : Configure the contact form to send an email confirmation to users upon successful submission. This email should provide a reference number or any other relevant details.

- [x] location section

- [x] Contact thanks page : After successful form submission, display a confirmation page or message to assure users that their inquiry or feedback has been received.

**Screenshots**
contact page
thanks

**Link to the component on Figma**
Contact page https://www.figma.com/file/4OUnD74RgIW6tsUFdb7gcW/Untitled?type=design&node-id=2-5399&mode=design&t=l1V3IyeaM4ljOhfK-4

Thank you page https://www.figma.com/file/4OUnD74RgIW6tsUFdb7gcW/Untitled?node-id=2%3A5356&mode=dev

### PR DESCRIPTION
**Pull request by HabchiSidAli**
create contact and contactThankYou pages with responsive design

#14

# Related Issue

- Resolve #14

### CODE REVIEW

**Comment by M07am3dM** [comment]
screenshot
Hey @HabchiSidAli amazing work well done, but what you if the button in the small screen take the full width as the input, that's will look better don't you think.


<details><summary>Browser metadata</summary>





```
Path:      /contact
Browser:   Chrome 117.0.0.0 on Windows 10
Viewport:  1600 x 775 @1x
Language:  en-GB
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-56--innerspace.netlify.app%2Fcontact&os=Windows&os_version=10&browser=Chrome&browser_version=117.0&resolution=1600x775&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-56--innerspace.netlify.app/contact) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=6531854ae0d3fe00084b1ca1&commentID=65318d479cc6bc247a760899&resolution=resolved)

**Review by Lilicod — APPROVED** [review]
Nice work with the design @HabchiSidAli 👍

**Review by M07am3dM — APPROVED** [review]
Good work @HabchiSidAli, thank you.

**Review by meryem08 — APPROVED** [review]
Great work @HabchiSidAli  !! thank you

**Pull request merged**
