### PR TITLE
Fetch the payment cards info from firestore

### LINKED ISSUE #103: fetch the payment cards info from firestore
**Task title**
fetch the payment cards info 

**Task description**
fetch the cards info in the payment methods page and buy tickets page

### PR DESCRIPTION
**Pull request by Lilicod**
### changes 

- Fetch the cards info in the payments methods page and buy ticket page
- add A 'no cards message' when there's no saved cards in the data base

closes #103 

# Related Issue

- Resolve #103

### CODE REVIEW

**Comment by dalilia** [comment]
great job @Lilicod

**Review by dalilia — APPROVED** [review]
great job @Lilicod

**Review by HabchiSidAli — APPROVED** [review]
Well done @Lilicod, everything works as expected, the only thing is when the user has two cards added to their account there's a big gap between them.
image

**Comment by Lilicod** [comment]
> Well done @Lilicod, everything works as expected, the only thing is when the user has two cards added to their account there's a big gap between them. image

Thank you @HabchiSidAli, I noticed that, when the user has less than three cards the cards dispaear, so I tried to play around this by rendering either 3 or the cards number, it worked but the style is not the best, there isn't much I can do about this. if you have any suggestion to fix this let me know

**Pull request merged**
