### PR TITLE
creat navbar component

### LINKED ISSUE #10: Navbar-component
**Task title**
Navbar-component

**Task description**
Creat the navbar component

**Subtasks**

- [x] add logo
- [x] Home link
- [x] Blogs link
- [x] about dropdown
- [x] contact us link
- [x] Log In button

**Screenshots**
navbar

**Link to the component on Figma**
Put the link here

### PR DESCRIPTION
**Pull request by Lilicod**
**Changes Made:**

**Responsive Design:**

Implement a responsive design using Tailwind CSS to ensure that the navbar adapts seamlessly to different screen sizes, including mobile and tablet (sm and md breakpoints).

**Translation Functionality:**

Integrate the useTranslation hook from next-i18next to enable dynamic translation of the navbar's text content.
Implement translations for the following elements:

- Navigation links.
- Dropdown menu items.

**Integration:**

Integrate the Navbar component into the appropriate pages on our website, ensuring it works cohesively with the overall design.

lg :
Capture d’écran 2023-10-18 221955

md:
Capture d’écran 2023-10-18 222023

sm:
Capture d’écran 2023-10-18 222049
Capture d’écran 2023-10-18 222139

# Related Issue

- Resolve #10

### CODE REVIEW

**Review by dzc0d3r — APPROVED** [review]
Great Work @Lilicod :100: 
Thank You

**Comment by M07am3dM** [comment]
<details><summary>Comment has been resolved by Mohamed Matassi</summary>

screenshot
Nice work with the English/Arabic translation, well done.

<details><summary>Browser metadata</summary>





```
Path:      /ar
Browser:   Chrome 117.0.0.0 on Windows 10
Viewport:  1600 x 775 @1x
Language:  en-GB
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-51--innerspace.netlify.app%2Far&os=Windows&os_version=10&browser=Chrome&browser_version=117.0&resolution=1600x775&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-51--innerspace.netlify.app/ar) · [Mark as Unresolved](https://app.netlify.com/cdp/resolve?deployID=65305084d791710008378cd9&commentID=6530557591b04b105f6b2ec3&resolution=unresolved)

</details>

**Comment by dzc0d3r** [comment]
<details><summary>Comment has been resolved by Walid Lamraoui</summary>

I think the dropdown is far to the right, can we move it to the left? what do you think @Lilicod ?

screenshot

Overall amazing work @Lilicod 💯 
<details><summary>Browser metadata</summary>





```
Path:      /
Browser:   Firefox 115.0 on Linux x86_64
Viewport:  1366 x 615 @1x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-51--innerspace.netlify.app%2F&os=OS%20X&os_version=Big%20Sur&browser=Firefox&browser_version=115.0&resolution=1366x615&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-51--innerspace.netlify.app/) · [Mark as Unresolved](https://app.netlify.com/cdp/resolve?deployID=65305084d791710008378cd9&commentID=6530558c10813816f97496cc&resolution=unresolved)

</details>

**Review by M07am3dM — APPROVED** [review]
Good work @Lilicod , thank you.

**Pull request merged**
