### PR TITLE
add purchase tickets and are you councelor sections

### LINKED ISSUE #26: Home Page section 5 : Purchase tickets
**Task title**
Purchase tickets section

**Description**
---
Purchase tickets section where the ticket can be used to book appointement with irresistible discounts for multiple times.

**Subtasks**

- [x] #26

**Screenshot**
---
Screenshot 2023-10-19 102422

**Link**
---
Figma [design]https://www.figma.com/file/4OUnD74RgIW6tsUFdb7gcW/Untitled?node-id=2%3A6773&mode=dev

### LINKED ISSUE #27: Home page section 6 : Are you a counselor?
**Description** 
---
Create are you a counselor section as a component.

**Screenshot**
---
Screenshot 2023-10-17 at 18-04-54 Figma

**Figma Design** 
---
[Link to the section](https://www.figma.com/file/ae4wheNUlDfAcNOmxj13Xy/Online-Therapist?type=design&node-id=279-4746&mode=design&t=qYStLtWLoLLKZtE9-4)

### PR DESCRIPTION
**Pull request by dzc0d3r**
**Description** 
---
Add purchase tickets and are you a councelor sections 

**Screenshot**
---

**Large Screens**

Screenshot 2023-10-18 at 00-11-05 Screenshot

**Medium**

Screenshot 2023-10-18 at 00-12-16 Screenshot

**Small**

Screenshot 2023-10-18 at 00-17-40 Screenshot

# Related Issue

- Resolve #26

### CODE REVIEW

**Review by dzc0d3r — COMMENTED** [review]
@Lilicod , @M07am3dM 
Please review this PR ASAP

**Comment by M07am3dM** [comment]
Nice work @dzc0d3r, especially with the responsiveness, well done.

**Review by M07am3dM — APPROVED** [review]
Good work @dzc0d3r, thank you.

**Comment by dzc0d3r** [comment]
Thank you @M07am3dM for the review :1st_place_medal:

**Review by Lilicod — APPROVED** [review]
Great job 💯

**Pull request merged**
