### PR TITLE
deploy the project to vercel

### LINKED ISSUE #6: deploy the project
**Task title**
deploy the project

**Task description**
deploy the project  to continuously test the website in a real environment. This helps in identifying and addressing issues as they arise, reducing the chances of major problems surfacing later.

**Subtasks**

- [x] Deploy the project to Vercel or Netlify

### PR DESCRIPTION
**Pull request by M07am3dM**
deploy the project to vercel and enabling the preview comments, also add the link in the description and the readme file

fix #6

# Related Issue

- Resolve #6

### CODE REVIEW

**Comment by M07am3dM** [comment]
hey @dzc0d3r and @Lilicod, please checkout this pull request.

**Comment by dzc0d3r** [comment]
Hi @M07am3dM , 
**Great work** :100: :tada:  .. however when i tried to log in to comment it asked me for access which i requested .. i am waiting for the approval.
BTW .. I don't know if it's better if we limit the access to the preview to team members only or not ? what's your thought about the matter? for instance we can allow everyone with the link .. but add password protection so only who have the  password can review and comment  .

**Review by dzc0d3r — APPROVED** [review]
Amazing :100: 
Thank you @M07am3dM

**Comment by M07am3dM** [comment]
Hey @dzc0d3r , first of you are welcome, glad you like the work.
- I thought about too and i think is also has some benefits if we allows the ones with the link to add a preview comments.
- Also i did the deploy with my an account related to my GitHub, and after that noticed it and did another one with new Vercel account opened with our project email, so do i need to push the new one or we just keep as it is.

**Comment by dzc0d3r** [comment]
@M07am3dM ,
 It's okay as it is at least for now, however for the access part let's discuss the subject on today's meeting :100:

**Review by Lilicod — APPROVED** [review]
Great job 💯

**Comment by M07am3dM** [comment]
@Lilicod  check this please
https://vercel.live/link/online-therapist-git-6-deploy-the-project-m07am3dms-projects.vercel.app?page=%2F%3FvercelThreadId%3Dfihwp&via=in-app-copy-link

**Pull request closed without merging**
