### PR TITLE
Footer component

### LINKED ISSUE #11: Footer-component
**Task title**
Footer-component

**Task description**
Creat the footer component

**Subtasks**

- [x] subscribe field
- [x] page links
- [x] socials icons

**Screenshots**
footerr

**Link to the component on Figma**
https://www.figma.com/file/4OUnD74RgIW6tsUFdb7gcW/Untitled?type=design&node-id=2-6892&mode=design&t=YB5vmlBgRYGp1CFQ-4

### PR DESCRIPTION
**Pull request by meryem08**
Created the Footer component along with the tests

Fixes #11

## Screenshots

- Large screen
Large Screen

- Medium Screen
Medium Screen

- Small screen
Small Screen

# Related Issue

- Resolve #11

### CODE REVIEW

**Comment by M07am3dM** [comment]
<details><summary>Comment has been resolved by Mohamed Matassi</summary>

screenshot
Nice design and good work @meryem08, why the background color black and doesn't match the screenshots, also the contents referred with arrows need to be centered in the small screen, thank you.


<details><summary>Browser metadata</summary>





```
Path:      /
Browser:   Chrome 117.0.0.0 on Windows 10
Viewport:  1600 x 775 @1x
Language:  en-GB
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-54--innerspace.netlify.app%2F&os=Windows&os_version=10&browser=Chrome&browser_version=117.0&resolution=1600x775&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-54--innerspace.netlify.app/) · [Mark as Unresolved](https://app.netlify.com/cdp/resolve?deployID=65306e95db4c540008219ccc&commentID=653073c5acdcd834c7c8eaf1&resolution=unresolved)

</details>

**Comment by meryem08** [comment]
Remove the dark mode style and adjust the style of some elements: center them.

Fixes #11 

## Screenshots

- Large screen
Large Screen

- Medium Screen
Medium Screen

- Small screen
Small Screen

@M07am3dM

**Comment by M07am3dM** [comment]
good, thank you... .

**Comment by meryem08** [comment]
Adjust the style of some elements

Fixes #11 

## Screenshots



- Medium Screen
Medium Screen



- Small screen
Small Screen

**Comment by M07am3dM** [comment]
Even better @meryem08, great work, well done.

**Review by M07am3dM — APPROVED** [review]
Great work @meryem08, thank you.

**Review by Lilicod — APPROVED** [review]
well done @meryem08, I love the design for the medium and small screen 💯 👏

**Pull request merged**
