### PR TITLE
Creat buy ticket page

### LINKED ISSUE #32: Buy Ticket
**Task title**
Buy Ticket

**Task description**
 This page allows users to select their preferred payment card and proceed with purchasing a ticket.

**Subtasks**

- [x] Card Selection: Users should be able to select from their saved payment cards. The page must display a list of cards associated with their account.
- [x] Confirmation: Once users confirm their selection, there should be a confirmation message.
- [x] Create Ticket thanks page.

**Screenshots**
Capture d’écran 2023-10-15 004635
Capture d’écran 2023-10-15 004653

**Link to the component on Figma**
https://www.figma.com/file/4OUnD74RgIW6tsUFdb7gcW/Untitled?type=design&node-id=2-6686&mode=design&t=iYcMyvxa9t3sNrbw-4

### PR DESCRIPTION
**Pull request by Lilicod**
## Description

This pull request introduces a new Buy Ticket page that enhances the user experience by allowing them to select a payment card and confirm their ticket purchase. It also includes the feature to display a thank you page upon successful confirmation.

## Changes Made

- Added a new `BuyTicket` page.
- Integrated a responsive card slider to display available payment cards.
- Implemented the ability for users to select a payment card by clicking on it.
- Added validation to ensure that the user selects a card before confirming the purchase.
- Included a 'Confirm' button, which takes the user to a thank you page upon successful confirmation.

## Screenshots

buy
Capture d’écran 2023-10-29 202638

## Related Issues

fix #32

### CODE REVIEW

**Review by dzc0d3r — APPROVED** [review]
Amazing job @Lilicod :100:
Thank you

**Review by HabchiSidAli — APPROVED** [review]
Looks good. Thank you @Lilicod.

**Review by M07am3dM — APPROVED** [review]
Great work @Lilicod well done, however i think the colors of the cards should be deferent and as the real once or similar, thank you.

**Comment by dalilia** [comment]
great job @Lilicod :)

**Pull request merged**
