### PR TITLE
create login page

### LINKED ISSUE #17: login page
**Task title**
login page

**Task description**
the Login page will support multiple login methods. Users will have the flexibility to choose their preferred method, enhancing the accessibility, This issue involves integrating Firebase Authentication methods for email, Facebook, and Google.

**Subtasks**

- [x] Input : Create a reusable input to work with in all the forms.

- [x] Email Login : Implement Firebase's email/password authentication, allowing users to log in using their email addresses. Ensure secure access to user accounts and proper error handling.

- [x] Facebook Login : Integrate Firebase with Facebook authentication. Users will have the option to log in using their Facebook accounts. 

- [x] Google Login : Implement Firebase's Google authentication, allowing users to log in with their Google accounts. Safely manage user data and maintain consistency in the login process.

**Screenshots**
login

**Link to the component on Figma**
https://www.figma.com/file/4OUnD74RgIW6tsUFdb7gcW/Untitled?type=design&node-id=2-6618&mode=design&t=3WJyDJ9tmMfJOBVl-4

### PR DESCRIPTION
**Pull request by M07am3dM**
create login page and adding a form with email and password singin, also implement singin with google and facebook providers.

fix #17

### CODE REVIEW

**Review by HabchiSidAli — APPROVED** [review]
Amazing work @M07am3dM, but there's just one thing, could you just make so that when the user presses log in, he gets those input fields are required messages, instead of getting them as soon as he presses on any input field, thank you.

**Review by Lilicod — APPROVED** [review]
Great job @M07am3dM 💯, just one thing the input's error message should apear when clicking on the button and not the input itself, other than that all looks good, thank you 👍

**Comment by M07am3dM** [comment]
Thank you @HabchiSidAli for your amazing feedback, yes you right, i will work on it.

**Comment by M07am3dM** [comment]
Hey @HabchiSidAli ,@Lilicod , done, i fixed the inputs error message, thank you for your amazing feedback.

**Review by dzc0d3r — COMMENTED** [review]
great work @M07am3dM

**Pull request merged**
