### PR TITLE
create about page

### LINKED ISSUE #13: about page
**Task title**
about page

**Task description**
Creat the about page that provides users with an overview of our website, our team, and our journey. This will build trust, engage users, and foster a stronger connection

**Subtasks**

- [ ] Brand Overview : Provide a brief yet comprehensive introduction to our website, including our mission, vision, and core values.

- [ ] enhance the design : Ensure that the page's design is visually appealing

**Screenshots**
about

**Link to the component on Figma**
https://www.figma.com/file/4OUnD74RgIW6tsUFdb7gcW/Untitled?type=design&node-id=2-6438&mode=design&t=l1V3IyeaM4ljOhfK-4

### PR DESCRIPTION
**Pull request by dalilia**

### CODE REVIEW

**Review by Lilicod — APPROVED** [review]
Great job @dalilia,

**Comment by M07am3dM** [comment]
<details><summary>Comment has been resolved by Mohamed Matassi</summary>

screenshot
Nice work @dalilia, however you need to work more on the design, thank you.


<details><summary>Browser metadata</summary>





```
Path:      /about
Browser:   Chrome 117.0.0.0 on Windows 10
Viewport:  1600 x 775 @1x
Language:  en-GB
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-50--innerspace.netlify.app%2Fabout&os=Windows&os_version=10&browser=Chrome&browser_version=117.0&resolution=1600x775&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-50--innerspace.netlify.app/about) · [Mark as Unresolved](https://app.netlify.com/cdp/resolve?deployID=65304c26ddec630007adef64&commentID=65305981ec7a561a1696db08&resolution=unresolved)

</details>

**Review by M07am3dM — CHANGES_REQUESTED** [review]
Hey @dalilia, can you  please see what is happening the text and the EN/AR translation, thank you.

**Review by M07am3dM — APPROVED** [review]

**Comment by M07am3dM** [comment]
nice work @dalilia well done, just please fix prettier and test issues in your local environment and make new commit, thank you.

**Pull request merged**
