### PR TITLE
make Button component

### PR DESCRIPTION
**Pull request by HabchiSidAli**
Changes Made:

Make a button component with multiple styles and variants, with animated hover effects and a disabled state.

### CODE REVIEW

**Review by Lilicod — APPROVED** [review]
Great job 💯   @HabchiSidAli, thank you

**Review by dzc0d3r — APPROVED** [review]
Great Work @HabchiSidAli  :100: 
Thank You

**Review by M07am3dM — CHANGES_REQUESTED** [review]
Nice work @HabchiSidAli, well done.

**Review by M07am3dM — APPROVED** [review]

**Review by meryem08 — APPROVED** [review]
Nice work @HabchiSidAli

**Pull request merged**
